import type { CategoryDto, ListingCardDto, ListingsPage } from "./catalog";

export interface MockListing extends ListingCardDto {
  oldPrice?: number;
  rating: number;
  reviewsCount: number;
  badge?: "new" | "hot" | "sale" | "best";
  gradient: string;
  emoji: string;
}

export const mockCategories: CategoryDto[] = [
  { id: "cat-women", slug: "women", name: "Женщинам", icon: "👗", order: 1 },
  { id: "cat-men", slug: "men", name: "Мужчинам", icon: "👔", order: 2 },
  { id: "cat-beauty", slug: "beauty", name: "Красота", icon: "💄", order: 3 },
  { id: "cat-electronics", slug: "electronics", name: "Электроника", icon: "📱", order: 4 },
  { id: "cat-home", slug: "home", name: "Дом", icon: "🏡", order: 5 },
  { id: "cat-kids", slug: "kids", name: "Детям", icon: "🧸", order: 6 },
  { id: "cat-sport", slug: "sport", name: "Спорт", icon: "⚽", order: 7 },
  { id: "cat-books", slug: "books", name: "Книги", icon: "📚", order: 8 },
  { id: "cat-food", slug: "food", name: "Продукты", icon: "🛒", order: 9 },
  { id: "cat-auto", slug: "auto", name: "Авто", icon: "🚗", order: 10 },
];

function catOf(slug: string): ListingCardDto["category"] {
  const c = mockCategories.find((x) => x.slug === slug)!;
  return { id: c.id, slug: c.slug, name: c.name };
}

export const mockListings: MockListing[] = [
  {
    id: "m-1",
    title: "Платье миди из вискозы с поясом",
    price: 4_990_00,
    oldPrice: 7_490_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 12,
    category: catOf("women"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    rating: 4.8,
    reviewsCount: 214,
    badge: "sale",
    gradient: "from-rose-200 via-amber-200 to-orange-200",
    emoji: "👗",
  },
  {
    id: "m-2",
    title: "Кроссовки дышащие, повседневные",
    price: 6_490_00,
    oldPrice: 8_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Санкт-Петербург",
    imageUrl: null,
    stock: 8,
    category: catOf("men"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    rating: 4.7,
    reviewsCount: 412,
    badge: "hot",
    gradient: "from-amber-200 via-orange-200 to-rose-200",
    emoji: "👟",
  },
  {
    id: "m-3",
    title: "Набор ухода за кожей лица",
    price: 2_790_00,
    oldPrice: 3_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Казань",
    imageUrl: null,
    stock: 22,
    category: catOf("beauty"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    rating: 4.9,
    reviewsCount: 1583,
    badge: "best",
    gradient: "from-pink-200 via-rose-200 to-orange-100",
    emoji: "💆",
  },
  {
    id: "m-4",
    title: "Смарт-часы Active с пульсометром",
    price: 9_990_00,
    oldPrice: 14_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 5,
    category: catOf("electronics"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    rating: 4.6,
    reviewsCount: 827,
    badge: "sale",
    gradient: "from-orange-200 via-amber-100 to-yellow-100",
    emoji: "⌚",
  },
  {
    id: "m-5",
    title: "Сумка женская кожаная, среднего размера",
    price: 5_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 14,
    category: catOf("women"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    rating: 4.7,
    reviewsCount: 302,
    badge: "new",
    gradient: "from-orange-200 via-rose-200 to-pink-100",
    emoji: "👜",
  },
  {
    id: "m-6",
    title: "Беспроводные наушники с ANC",
    price: 7_490_00,
    oldPrice: 9_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Новосибирск",
    imageUrl: null,
    stock: 9,
    category: catOf("electronics"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    rating: 4.5,
    reviewsCount: 1122,
    badge: "hot",
    gradient: "from-amber-100 via-orange-200 to-red-200",
    emoji: "🎧",
  },
  {
    id: "m-7",
    title: "Термокружка с подогревом 500 мл",
    price: 1_890_00,
    oldPrice: 2_490_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Екатеринбург",
    imageUrl: null,
    stock: 42,
    category: catOf("home"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    rating: 4.8,
    reviewsCount: 560,
    gradient: "from-yellow-100 via-amber-200 to-orange-200",
    emoji: "☕",
  },
  {
    id: "m-8",
    title: "Конструктор развивающий, 120 деталей",
    price: 1_290_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 33,
    category: catOf("kids"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 42).toISOString(),
    rating: 4.9,
    reviewsCount: 211,
    badge: "new",
    gradient: "from-orange-100 via-amber-100 to-rose-100",
    emoji: "🧩",
  },
  {
    id: "m-9",
    title: "Мяч футбольный профессиональный",
    price: 2_190_00,
    oldPrice: 2_790_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Сочи",
    imageUrl: null,
    stock: 26,
    category: catOf("sport"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    rating: 4.6,
    reviewsCount: 98,
    gradient: "from-amber-200 via-orange-100 to-yellow-200",
    emoji: "⚽",
  },
  {
    id: "m-10",
    title: "Книга: Психология для всех",
    price: 690_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 120,
    category: catOf("books"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 54).toISOString(),
    rating: 4.8,
    reviewsCount: 4203,
    badge: "best",
    gradient: "from-rose-100 via-orange-100 to-amber-100",
    emoji: "📖",
  },
  {
    id: "m-11",
    title: "Набор кухонных ножей 5 шт. на подставке",
    price: 4_590_00,
    oldPrice: 6_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Краснодар",
    imageUrl: null,
    stock: 18,
    category: catOf("home"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
    rating: 4.7,
    reviewsCount: 330,
    badge: "sale",
    gradient: "from-amber-200 via-yellow-100 to-orange-100",
    emoji: "🍽",
  },
  {
    id: "m-12",
    title: "Парфюмерная вода женская, 50 мл",
    price: 3_490_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 15,
    category: catOf("beauty"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
    rating: 4.9,
    reviewsCount: 1284,
    badge: "best",
    gradient: "from-rose-100 via-pink-100 to-amber-100",
    emoji: "🌸",
  },
  {
    id: "m-13",
    title: "Рубашка мужская оксфорд, хлопок",
    price: 3_290_00,
    oldPrice: 4_490_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 40,
    category: catOf("men"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 78).toISOString(),
    rating: 4.6,
    reviewsCount: 520,
    gradient: "from-amber-100 via-orange-100 to-rose-200",
    emoji: "👔",
  },
  {
    id: "m-14",
    title: "Йога-коврик антискользящий 6 мм",
    price: 1_690_00,
    oldPrice: 2_190_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Санкт-Петербург",
    imageUrl: null,
    stock: 60,
    category: catOf("sport"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 90).toISOString(),
    rating: 4.8,
    reviewsCount: 731,
    gradient: "from-orange-100 via-rose-100 to-amber-200",
    emoji: "🧘",
  },
  {
    id: "m-15",
    title: "Смартфон 128 ГБ, 6.6'' AMOLED",
    price: 24_990_00,
    oldPrice: 31_990_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 4,
    category: catOf("electronics"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 100).toISOString(),
    rating: 4.7,
    reviewsCount: 2144,
    badge: "hot",
    gradient: "from-yellow-100 via-amber-200 to-orange-300",
    emoji: "📱",
  },
  {
    id: "m-16",
    title: "Кофе в зёрнах премиум, 1 кг",
    price: 1_290_00,
    currency: "RUB",
    status: "PUBLISHED",
    city: "Москва",
    imageUrl: null,
    stock: 200,
    category: catOf("food"),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 110).toISOString(),
    rating: 4.9,
    reviewsCount: 3342,
    badge: "best",
    gradient: "from-amber-200 via-orange-200 to-rose-200",
    emoji: "☕",
  },
];

export function mockListingsPage(params: {
  categoryId?: string;
  q?: string;
  page?: number;
  limit?: number;
}): ListingsPage {
  const { categoryId, q, page = 1, limit = 16 } = params;
  let items = mockListings as ListingCardDto[];
  if (categoryId) items = items.filter((i) => i.category.id === categoryId);
  if (q) {
    const s = q.toLowerCase();
    items = items.filter(
      (i) => i.title.toLowerCase().includes(s) || i.category.name.toLowerCase().includes(s),
    );
  }
  const total = items.length;
  const pages = Math.max(1, Math.ceil(total / limit));
  const start = (page - 1) * limit;
  return {
    items: items.slice(start, start + limit),
    total,
    page,
    limit,
    pages,
  };
}
