-- Add LOGIN_VERIFICATION to EmailCodePurpose enum
ALTER TYPE "EmailCodePurpose" ADD VALUE IF NOT EXISTS 'LOGIN_VERIFICATION';

-- Add LOGIN_VERIFICATION to SmsCodePurpose enum
ALTER TYPE "SmsCodePurpose" ADD VALUE IF NOT EXISTS 'LOGIN_VERIFICATION';
